<?php
/**
 * Created by PhpStorm.
 * User: dmitriy
 * Date: 2019-10-28
 * Time: 13:42
 */

namespace Mytest\Elevator\Controller\Adminhtml;

use Magento\Backend\App\Action;
use Magento\Backend\App\Action\Context;
use Magento\Framework\View\Result\PageFactory;
use Magento\Framework\Controller\ResultFactory;
use Magento\Framework\Session\SessionManagerInterface;

use Mytest\Elevator\Model\BaseElevatorFactory;
use Mytest\Elevator\Api\BaseElevatorRepositoryInterface as Repository;

/**
 * Class AbstractElevator
 * @package Mytest\Elevator\Controller\Adminhtml
 */
abstract class AbstractElevator extends Action
{
    const ACL_RESOURCE          = "Mytest_Elevator::main_menu";
    const QUERY_PARAM_ID        = 'id';
    const TITLE                 = 'Elevator module';
    const BREADCRUMB_TITLE      = 'ELevator';
    /**
     * @var $model
     */
    protected $model;
    protected $elevatorFactory;
    /**
     * @var
     */
    protected $resultPage;
    /**
     * @var Repository
     */
    protected $repository;
    /**
     * @var SessionManagerInterface
     */
    protected $sessionManager;
    /**
     * @var PageFactory
     */
    protected $pageFactory;


    public function __construct(BaseElevatorFactory $baseElevatorFactory,
                                PageFactory $pageFactory,
                                SessionManagerInterface $sessionManager,
                                Repository $repository,
                                Context $context
    ) {
        $this->elevatorFactory = $baseElevatorFactory;
        $this->pageFactory     = $pageFactory;
        $this->sessionManager  = $sessionManager;
        $this->repository      = $repository;
                parent::__construct($context);
    }


    /**
     * @return \Magento\Framework\View\Result\Page
     */
    protected function _getResultPage()
    {
        if (null === $this->resultPage) {
            $this->resultPage = $this->pageFactory->create();
        }
        return $this->resultPage;
    }

    /**
     * @return \Magento\Framework\App\ResponseInterface|\Magento\Framework\Controller\ResultInterface
     */
    public function execute()
    {
        $this->_setPageData();
        return $this->resultPage;
    }

    /**
     * @return $this
     */
    protected function _setPageData()
    {
        $resultPage = $this->_getResultPage();
        $resultPage->getConfig()->getTitle()->prepend((__(static::TITLE)));
        $resultPage->addBreadcrumb(__(static::BREADCRUMB_TITLE), __(static::BREADCRUMB_TITLE));
        $resultPage->addBreadcrumb(__(static::BREADCRUMB_TITLE), __(static::BREADCRUMB_TITLE));
        return $this;
    }

    /**
     * @return bool
     */
    public function _isAllowed()
    {
        $result = parent::_isAllowed(); // TODO: Change the autogenerated stub
        $result = $result && $this->_authorization->isAllowed($this::ACL_RESOURCE);
        return $result;
    }

    /**
     * @return \Magento\Framework\App\ResponseInterface
     */
    protected function redirectToGrid()
    {
        return $this->_redirect('*/*/listing');
    }
    protected function doRefererRedirect()
    {
        $redirect = $this->resultFactory->create(ResultFactory::TYPE_REDIRECT);
        $redirect->setUrl($this->_redirect->getRefererUrl());
        return $redirect;
    }
    protected function getModel()
    {
        if($this->model === null) {
            return $this->elevatorFactory->create();
        } else return $this->model;
    }
}
